trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'

steps:
    - script: npm install  
      workingDirectory: frontend  
      displayName: 'frontend install dependencies'

    - script: npm run build:staging
      workingDirectory: frontend
      displayName: 'frontend staging build'

    - task: ArchiveFiles@2
      inputs:
        rootFolderOrFile: 'frontend/build'
        includeRootFolder: false
        archiveType: zip
        archiveFile: '$(Build.ArtifactStagingDirectory)/frontend-staging/build.zip'
        replaceExistingArchive: true
      displayName: 'frontend staging zip files'

    - task: ArchiveFiles@2
      inputs:
        rootFolderOrFile: 'frontend/cypress'
        includeRootFolder: false
        archiveType: zip
        archiveFile: '$(Build.ArtifactStagingDirectory)/frontend-staging/tests.zip'
        replaceExistingArchive: true
      displayName: 'frontend cypress zip files'

    - task: PublishBuildArtifacts@1
      inputs:
        pathtoPublish: '$(Build.ArtifactStagingDirectory)/frontend-staging'
        artifactName: 'frontend-staging'
      displayName: 'frontend staging publish to pipeline'

    - script: npm run build:production
      workingDirectory: frontend
      displayName: 'frontend production build'

    - task: ArchiveFiles@2
      inputs:
        rootFolderOrFile: 'frontend/build'
        includeRootFolder: false
        archiveType: zip
        archiveFile: '$(Build.ArtifactStagingDirectory)/frontend-production/build.zip'
        replaceExistingArchive: true
      displayName: 'frontend production zip files'

    - task: PublishBuildArtifacts@1
      inputs:
        pathtoPublish: '$(Build.ArtifactStagingDirectory)/frontend-production'
        artifactName: 'frontend-production'
      displayName: 'frontend production publish to pipeline'
