# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- task: UseDotNet@2
  inputs:
    version: '5.0.100'
    packageType: 'sdk'

- script: dotnet build --configuration $(buildConfiguration)  
  workingDirectory: backend  
  displayName: 'backend build'

- script: dotnet test  
  workingDirectory: backend  
  displayName: 'backendtests build'

- task: DotNetCoreCLI@2
  displayName: 'dotnet publish $(buildConfiguration)'
  inputs:
    command: publish
    publishWebProjects: False
    arguments: '--self-contained --runtime win-x86 --configuration $(BuildConfiguration)'

- script: npm install  
  workingDirectory: frontend  
  displayName: 'frontend install dependencies'

- script: npm run test:ci  
  workingDirectory: frontend  
  displayName: 'frontend tests'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: 'backend/bin/Release/net5.0/win-x86/publish'
    includeRootFolder: false
    archiveType: zip
    archiveFile: '$(Build.ArtifactStagingDirectory)/backend/$(Build.BuildId).zip'
    replaceExistingArchive: true
  displayName: 'backend zip files'

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)/backend'
    artifactName: 'backend' 
  displayName: 'backend publish to pipeline'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: 'frontend/build'
    includeRootFolder: false
    archiveType: zip
    archiveFile: '$(Build.ArtifactStagingDirectory)/frontend-staging/build.zip'
    replaceExistingArchive: true
  displayName: 'frontend staging zip files'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: 'frontend/cypress'
    includeRootFolder: false
    archiveType: zip
    archiveFile: '$(Build.ArtifactStagingDirectory)/frontend-staging/tests.zip'
    replaceExistingArchive: true
  displayName: 'frontend cypress zip files'

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)/frontend-staging'
    artifactName: 'frontend-staging'
  displayName: 'frontend staging publish to pipeline'

- script: npm run build:production
  workingDirectory: frontend
  displayName: 'frontend production build'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: 'frontend/build'
    includeRootFolder: false
    archiveType: zip
    archiveFile: '$(Build.ArtifactStagingDirectory)/frontend-production/build.zip'
    replaceExistingArchive: true
  displayName: 'frontend production zip files'

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)/frontend-production'
    artifactName: 'frontend-production'
  displayName: 'frontend production publish to pipeline'
